//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAccounting.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persons
    {
        public int PersonId { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Mobile { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Address { get; set; }
        public string Image { get; set; }
    }
}
